"""Integration tests: real video files through the real pipeline.

The videos are generated by :mod:`tests.conftest` with known ground truth, so
these assert *measured timings against what was drawn*, not merely that the
code runs.
"""

from __future__ import annotations

import time
from pathlib import Path

import pytest

from app.analysis.base_detector import null_progress
from app.analysis.coarse_scan import plan_coarse_scan, run_coarse_scan
from app.analysis.motion_detector import MotionActivityScorer
from app.analysis.registry import available_modes, create_detector
from app.analysis.zahn_detector import build_roi_from_click
from app.config import ROI, CoarseScanConfig, ZahnConfig
from app.errors import EmptyVideoError, InvalidROIError, VideoOpenError
from app.services.event_log import build_event_log
from app.video.metadata import probe_video
from app.video.reader import VideoReader


class TestMetadata:
    def test_probe_reports_the_truth(self, motion_video):
        info = probe_video(motion_video.path)
        assert info.width == motion_video.width
        assert info.height == motion_video.height
        assert info.fps == pytest.approx(motion_video.fps, abs=0.01)
        assert info.duration_s == pytest.approx(motion_video.duration_s, abs=0.2)
        assert info.fps_source == "container"
        assert info.size_bytes > 0

    def test_corrupt_file_is_rejected_clearly(self, broken_video: Path):
        with pytest.raises((VideoOpenError, EmptyVideoError)) as excinfo:
            probe_video(broken_video)
        # The message must be readable by a non-programmer.
        assert "video" in excinfo.value.user_message.lower()

    def test_missing_file_is_rejected(self, tmp_path: Path):
        with pytest.raises(VideoOpenError):
            probe_video(tmp_path / "nope.mp4")

    def test_empty_file_is_rejected(self, tmp_path: Path):
        empty = tmp_path / "empty.mp4"
        empty.write_bytes(b"")
        with pytest.raises(EmptyVideoError):
            probe_video(empty)


class TestReader:
    def test_sampling_decodes_only_the_requested_frames(self, motion_video):
        """Frame skipping must actually skip decoding, not just discard."""
        info = probe_video(motion_video.path)
        plan = plan_coarse_scan(info, CoarseScanConfig(shortest_event_s=6.0))
        with VideoReader(motion_video.path, info) as reader:
            samples = list(reader.iter_samples(plan))
        total_frames = int(motion_video.duration_s * motion_video.fps)
        assert len(samples) < total_frames / 10
        assert reader.stats.frames_decoded == len(samples)

    def test_downscaling_is_applied(self, motion_video):
        info = probe_video(motion_video.path)
        config = CoarseScanConfig(scan_width_px=80)
        plan = plan_coarse_scan(info, config)
        with VideoReader(motion_video.path, info) as reader:
            sample = next(iter(reader.iter_samples(plan)))
        assert sample.image.shape[1] == 80
        assert sample.image.ndim == 2  # greyscale

    def test_roi_crop_is_applied_before_scaling(self, motion_video):
        info = probe_video(motion_video.path)
        roi = ROI(10, 20, 160, 120)
        plan = plan_coarse_scan(info, CoarseScanConfig(scan_width_px=160), roi=roi)
        with VideoReader(motion_video.path, info) as reader:
            sample = next(iter(reader.iter_samples(plan, roi=roi)))
        assert sample.image.shape == (120, 160)

    def test_seek_to_a_timestamp(self, motion_video):
        info = probe_video(motion_video.path)
        with VideoReader(motion_video.path, info) as reader:
            frame = reader.frame_at(6.0)
        assert frame.shape[:2] == (motion_video.height, motion_video.width)

    def test_memory_stays_flat_over_a_long_scan(self, motion_video):
        """The reader must never accumulate frames."""
        info = probe_video(motion_video.path)
        plan = plan_coarse_scan(info, CoarseScanConfig(shortest_event_s=3.0))
        with VideoReader(motion_video.path, info) as reader:
            held = [id(sample.image) for sample in reader.iter_samples(plan)]
        # Nothing is retained by the reader itself.
        assert reader.stats.frames_decoded == len(held)


class TestCoarseScan:
    def test_quiet_video_produces_no_candidates(self, quiet_video):
        info = probe_video(quiet_video.path)
        with VideoReader(quiet_video.path, info) as reader:
            result = run_coarse_scan(
                reader, MotionActivityScorer(), CoarseScanConfig(shortest_event_s=3.0)
            )
        assert result.candidates == []

    def test_two_motion_periods_are_found(self, motion_video):
        info = probe_video(motion_video.path)
        config = CoarseScanConfig(shortest_event_s=3.0, min_candidate_duration_s=0.5)
        with VideoReader(motion_video.path, info) as reader:
            result = run_coarse_scan(reader, MotionActivityScorer(), config)

        assert len(result.candidates) == 2
        first, second = result.candidates
        # Conservative boundaries: the true event must lie inside the window.
        assert first.start_s <= motion_video.truth["first_start_s"]
        assert first.end_s >= motion_video.truth["first_end_s"] - result.plan.effective_interval_s
        assert second.start_s <= motion_video.truth["second_start_s"]

    def test_scan_is_much_faster_than_real_time(self, motion_video):
        info = probe_video(motion_video.path)
        started = time.monotonic()
        with VideoReader(motion_video.path, info) as reader:
            run_coarse_scan(reader, MotionActivityScorer(), CoarseScanConfig(shortest_event_s=6.0))
        elapsed = time.monotonic() - started
        assert elapsed < motion_video.duration_s / 4


class TestGenericMotionDetector:
    def test_events_match_the_ground_truth(self, motion_video):
        info = probe_video(motion_video.path)
        detector = create_detector(
            "motion_scan",
            info,
            {
                "shortest_event_s": 3.0,
                "min_event_duration_s": 1.0,
                "pre_roll_s": 2.0,
                "post_roll_s": 2.0,
            },
        )
        with VideoReader(motion_video.path, info) as reader:
            result = detector.run(reader, null_progress)

        assert len(result.events) == 2
        first, second = result.events
        assert first.start_s == pytest.approx(motion_video.truth["first_start_s"], abs=0.6)
        assert first.end_s == pytest.approx(motion_video.truth["first_end_s"], abs=0.6)
        assert second.start_s == pytest.approx(motion_video.truth["second_start_s"], abs=0.6)
        assert second.end_s == pytest.approx(motion_video.truth["second_end_s"], abs=0.6)
        assert all(event.confidence > 0.4 for event in result.events)

    def test_refinement_is_more_accurate_than_the_coarse_pass(self, motion_video):
        """Stage B must actually improve on Stage A's boundaries."""
        info = probe_video(motion_video.path)
        config = CoarseScanConfig(shortest_event_s=6.0, min_candidate_duration_s=0.5)
        with VideoReader(motion_video.path, info) as reader:
            coarse = run_coarse_scan(reader, MotionActivityScorer(), config)

        detector = create_detector(
            "motion_scan", info, {"shortest_event_s": 6.0, "min_event_duration_s": 1.0}
        )
        with VideoReader(motion_video.path, info) as reader:
            refined = detector.run(reader, null_progress)

        truth = motion_video.truth["first_start_s"]
        coarse_error = abs(coarse.candidates[0].start_s - truth)
        refined_error = abs(refined.events[0].start_s - truth)
        assert refined_error < coarse_error

    def test_quiet_video_reports_nothing_and_says_so(self, quiet_video):
        info = probe_video(quiet_video.path)
        detector = create_detector("motion_scan", info, {"shortest_event_s": 3.0})
        with VideoReader(quiet_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        assert result.events == []
        assert any("No activity" in warning for warning in result.warnings)

    def test_progress_is_reported(self, motion_video):
        info = probe_video(motion_video.path)
        detector = create_detector("motion_scan", info, {"shortest_event_s": 3.0})
        updates: list[tuple[str, float]] = []

        def record(*, stage: str, fraction: float, message: str) -> None:
            updates.append((stage, fraction))

        with VideoReader(motion_video.path, info) as reader:
            detector.run(reader, record)

        assert updates
        assert updates[-1][1] == pytest.approx(1.0)
        assert {"scanning", "refining", "complete"} & {stage for stage, _ in updates}


class TestRobotActivityDetector:
    def test_reports_activity_and_the_pause_between(self, motion_video):
        info = probe_video(motion_video.path)
        detector = create_detector(
            "robot_activity",
            info,
            {"shortest_event_s": 3.0, "min_event_duration_s": 1.0, "idle_pause_s": 5.0},
        )
        with VideoReader(motion_video.path, info) as reader:
            result = detector.run(reader, null_progress)

        labels = [event.label for event in result.events]
        assert labels.count("Machine active") == 2
        assert "Extended pause" in labels

        pause = next(e for e in result.events if e.label == "Extended pause")
        # The scripted gap runs from 9 s to 18 s.
        assert pause.start_s == pytest.approx(9.0, abs=1.0)
        assert pause.end_s == pytest.approx(18.0, abs=1.0)

    def test_pause_reporting_can_be_switched_off(self, motion_video):
        info = probe_video(motion_video.path)
        detector = create_detector(
            "robot_activity", info, {"shortest_event_s": 3.0, "idle_pause_s": 0}
        )
        with VideoReader(motion_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        assert all(event.label != "Extended pause" for event in result.events)


class TestZahnDetector:
    def _detector(self, info, video, **params):
        base = {"outlet": {"x": int(video.truth["outlet_x"]), "y": int(video.truth["outlet_y"])}}
        base.update(params)
        return create_detector("zahn_cup", info, base)

    def test_efflux_time_matches_the_generated_video(self, zahn_video):
        info = probe_video(zahn_video.path)
        detector = self._detector(info, zahn_video)
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)

        summary = result.summary
        assert summary["flow_start_s"] == pytest.approx(zahn_video.truth["flow_start_s"], abs=0.3)
        assert summary["flow_end_s"] == pytest.approx(zahn_video.truth["flow_end_s"], abs=0.4)
        assert summary["efflux_seconds"] == pytest.approx(zahn_video.truth["efflux_s"], abs=0.5)
        assert summary["end_confirmed"] is True
        assert summary["status"] in {"confirmed", "review"}
        assert summary["fps"] == pytest.approx(zahn_video.fps, abs=0.01)
        assert summary["frames_analysed"] > 0

    def test_final_drops_are_not_mistaken_for_the_end(self, zahn_video):
        """Timing must run to the last drop, not to the first stream break."""
        info = probe_video(zahn_video.path)
        detector = self._detector(info, zahn_video)
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        # The continuous stream ends at 20 s; the last drop is at ~21.5 s.
        assert result.summary["flow_end_s"] > 20.5

    def test_analysis_stops_once_the_end_is_confirmed(self, zahn_video):
        """No point decoding the tail of the recording after the cup is empty."""
        info = probe_video(zahn_video.path)
        detector = self._detector(info, zahn_video)
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        total_frames = int(zahn_video.duration_s * zahn_video.fps)
        assert result.diagnostics["stopped_early"] is True
        assert result.summary["frames_analysed"] < total_frames

    def test_a_manual_region_works_as_well_as_a_click(self, zahn_video):
        info = probe_video(zahn_video.path)
        roi = build_roi_from_click(
            int(zahn_video.truth["outlet_x"]), int(zahn_video.truth["outlet_y"]), info, ZahnConfig()
        )
        detector = create_detector("zahn_cup", info, {"roi": roi.to_dict()})
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        assert result.summary["efflux_seconds"] == pytest.approx(
            zahn_video.truth["efflux_s"], abs=0.5
        )

    def test_no_stream_in_the_region_fails_instead_of_inventing_a_time(self, zahn_video):
        """Point the ROI at empty background: the honest answer is 'failed'."""
        info = probe_video(zahn_video.path)
        detector = create_detector(
            "zahn_cup", info, {"roi": ROI(x=10, y=250, width=60, height=200).to_dict()}
        )
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)

        assert result.summary["status"] == "failed"
        assert result.summary["efflux_seconds"] is None
        assert result.events == []
        assert result.warnings

    def test_missing_outlet_is_rejected_before_any_decoding(self, zahn_video):
        info = probe_video(zahn_video.path)
        with pytest.raises(InvalidROIError):
            create_detector("zahn_cup", info, {})

    def test_outlet_outside_the_frame_is_rejected(self, zahn_video):
        info = probe_video(zahn_video.path)
        with pytest.raises(InvalidROIError):
            create_detector("zahn_cup", info, {"outlet": {"x": 5000, "y": 5000}})

    def test_confidence_and_reasons_are_reported(self, zahn_video):
        info = probe_video(zahn_video.path)
        detector = self._detector(info, zahn_video)
        with VideoReader(zahn_video.path, info) as reader:
            result = detector.run(reader, null_progress)
        assert 0.0 < result.summary["confidence"] <= 0.98
        assert result.summary["reasons"]

    def test_end_persistence_setting_changes_the_result(self, zahn_video):
        """A too-short persistence stops at the first gap between drops."""
        info = probe_video(zahn_video.path)
        with VideoReader(zahn_video.path, info) as reader:
            impatient = self._detector(info, zahn_video, flow_end_persistence_s=0.1)
            impatient_result = impatient.run(reader, null_progress)
        with VideoReader(zahn_video.path, info) as reader:
            patient = self._detector(info, zahn_video, flow_end_persistence_s=0.5)
            patient_result = patient.run(reader, null_progress)

        assert impatient_result.summary["flow_end_s"] < patient_result.summary["flow_end_s"]


class TestEventLogFromRealRun:
    def test_csv_export_of_a_real_analysis(self, motion_video, tmp_path: Path):
        info = probe_video(motion_video.path)
        detector = create_detector("motion_scan", info, {"shortest_event_s": 3.0})
        with VideoReader(motion_video.path, info) as reader:
            result = detector.run(reader, null_progress)

        log = build_event_log(result.events, info, mode="motion_scan")
        csv_text = log.to_csv()
        destination = tmp_path / log.suggested_filename()
        destination.write_text(csv_text, encoding="utf-8")

        lines = [line for line in csv_text.splitlines() if line]
        assert len(lines) == len(result.events) + 1
        assert destination.exists()


class TestRegistry:
    def test_all_modes_are_listed(self):
        names = {mode["name"] for mode in available_modes()}
        assert names == {"zahn_cup", "robot_activity", "motion_scan"}

    def test_unknown_mode_is_rejected(self, motion_video):
        info = probe_video(motion_video.path)
        with pytest.raises(Exception) as excinfo:
            create_detector("magic_ai", info, {})
        assert "not available" in str(excinfo.value)

    def test_every_detector_describes_its_plan(self, motion_video):
        info = probe_video(motion_video.path)
        for mode in available_modes():
            params = {"outlet": {"x": 100, "y": 100}} if mode["name"] == "zahn_cup" else {}
            detector = create_detector(mode["name"], info, params)
            description = detector.describe()
            assert description["detector"] == mode["name"]
            assert description["video_fps"] > 0


class TestOptionalYolo:
    def test_missing_weights_reports_a_clear_error(self, tmp_path: Path):
        from app.errors import ModelUnavailableError
        from app.models.optional_yolo import load_object_detector

        with pytest.raises(ModelUnavailableError):
            load_object_detector(tmp_path / "absent.pt")

    def test_availability_check_does_not_raise(self):
        from app.models.optional_yolo import is_available

        assert isinstance(is_available(), bool)
